### ISSUE TITLE
Design: Moving in and out of enemy vision range after encountering enemy allows re-rolling combat initiative

### ISSUE THREAD

**Issue by Alphanumber** [ASteinheiser/react-rpg.com#17]
When seeing an enemy on the periphery of vision, the player can move out of sight before the enemy would otherwise start pathing towards the player. This allows the player to essentially re-roll for combat initiative to get the first strike by darting in and out of vision range if engaging in combat would not be optimal.

Opening this issue just to track discussions for any actions to take, if any are to be taken.

**Comment by ASteinheiser** [comment]
I feel like if your suggestion for new monster attack mechanics works out, this might be solved too. https://github.com/ASteinheiser/react-rpg.com/issues/21

**Comment by ASteinheiser** [comment]
@all-contributors please add @Alphanumber and @ASteinheiser for ideas

**Comment by ASteinheiser** [comment]
Closing to consolidate conversation in #21
