### ISSUE TITLE
Disable double-tap to zoom on iOS Safari

### ISSUE THREAD

**Issue by ASteinheiser** [ASteinheiser/react-rpg.com#19]
I tried the advice here, and still no luck!
https://stackoverflow.com/questions/51041393/how-to-disable-viewport-zooming-in-ios-11-3-safari

**Comment by ajrussellaudio** [comment]
Got a PR in for this.

**Comment by ASteinheiser** [comment]
Thanks man. I can't believe your solution was so simple, I don't know how I overlooked this. I even just did a search and found https://stackoverflow.com/questions/31343380/how-to-disable-the-double-tap-event-in-uiwebview which explains your solution. Turns out the iOS WebView is causing trouble.

And I just finished testing your changes on an actual device with the native app and it works. Stoked! I'll merge into master soon.
