### ISSUE TITLE
Some code review madness

### ISSUE THREAD

**Issue by JoniTech** [ASteinheiser/react-rpg.com#30]
This is absolutely amazing. I had a lot of fun reviewing the code. Thanks for letting us grow as developers by sharing your work!
Most of these are very subjective, feel free to ignore every one of these. And please do challenge me, I have no idea what I'm talking about half the time!

**1. Download app dialog in web view?**

https://github.com/ASteinheiser/react-rpg.com/blob/e438eb0e83c18498a48136356196159389cb9b4c/src/App.js#L38-L44

From the comment I guess the goal here was to only show the dialog to download the app in mobile view. It also shows in web view if the user hasn't opted out.

**2. Semantic UI**  
https://github.com/ASteinheiser/react-rpg.com/blob/33fd2963e5bead245ed3f8a95383c0aa1f0dd34d/src/components/download-app-popup/index.js#L44-L46
This is more of a generic remark, choose the proper HTML element when you can.
For example, try to avoid using divs + CSS to create buttons when you could be using button HTML elements or anchors. 
It improves the accessibility of the app a lot. I suspect for example that the fact that you use divs breaks the tabbing behavior. Which means you have no way of navigating the app without a mouse.
This might have been a design choice, but check out the React Bootstrap components, they are a good start or good inspiration when you review that. [https://react-bootstrap.github.io/](https://react-bootstrap.github.io/). You will also notice that you write a lot less duplicate code, because those atomic components have a bunch of presets that you can rely on.
Also read up on the HTML5 elements.

**3. Constants**
I personally am a fan of keeping constants in the relevant components, so I applaud you putting download URLs in the download pop-up. Not everyone shares my vision on that, since those decentralized constants don't tend to scale with the application. They become hard to find.
https://github.com/ASteinheiser/react-rpg.com/blob/e438eb0e83c18498a48136356196159389cb9b4c/src/App.js#L46-L58
This on the other hand needs some refactoring. Those magical numbers need to become constants. I would also refactor the code per function (large view, side menu).
There are more magic numbers and strings in the application, those should be constants for your future sanity.

**4. Fragment**
If you destructure Fragment, you can just write React and not React.Fragment. You can also use just `<>` and `</>`.
`import React, { Fragment } from 'react';`

**5. Abbreviations**
Watch out with abbreviations like showDl, it doesn't hurt to just write showDownloadPopUp. Your memory will get worse over the years, and while it might make sense in this context it might be confusing when you see it in the state.

**6. &&**
https://github.com/ASteinheiser/react-rpg.com/blob/e438eb0e83c18498a48136356196159389cb9b4c/src/App.js#L63
You can replace the ternary operator with && if one of the conditions is null. When you find yourself writing null a lot, consider if there is a better option or if your architecture is appropriate.

**7. Project structure**
I was a bit surprised at the project structure at first: components / features / modules. These might have very different meanings for different people. For example, could you not say that the spinner is a component? 
I think they usually recommend a technical split for small projects (see create-react-app or react-redux-starter-kit).
When you plan to scale, divide by functionality instead, as in monsters / world / maps. Kind of how you structured your reduces now.

**X. Probably ignore these**
- Maybe look into BEM naming conventions for your CSS
- Use relative units (Ex. em) instead of pixel values
- Since I saw that your CSS wasn't always in alphabetical order, let me share this wonderful video: [faCSSt](https://www.youtube.com/watch?v=WvBF1_-a5OY)
- When you start from dummy code, try renaming ids like root to something more descriptive. It will challenge you to understand the boilerplate better and will lower the risk of conflicts.
- Maybe the items should be functional components too, instead of constant objects? It would allow you to set up some validation and fix some enum types like the types ('weapon'). That could avoid hard to track bugs.
- The structure of the monsters feel strange too. I would expect the stats to be defined in the Monster component. Should we not be passing in stats to the Monster component. I see it more as the specialization case in the React docs [Specialization](https://reactjs.org/docs/composition-vs-inheritance.html#specialization), the Dragon being a special kind of Monster. I might be wrong on this one. Curious to get your vision on their structure.
- Maybe give your maps a functional name not only the number? Being descriptive is always a good thing.
- I noticed sometimes you use hooks and sometimes not for managing local state. Is that intentional?
- If you're going to pass around variables to a lot of components like largeView and sidemenu, maybe consider adding it to the state.
- Personally I'm not a big fan of keeping the index.js, I tend to rename those to have the same name as the folder. But it makes the import a bit more verbose.

**Comment by ASteinheiser** [comment]
Thank you for taking the time to review the code!
I am still intending on cleaning up the code quite a bit before I release the Roadmap.
I will be taking all of this into consideration as I go through a cleanup phase this weekend.

**Comment by ASteinheiser** [comment]
I believe I have implemented most of your advice in this branch. Check it out and let me know what you think!
https://github.com/ASteinheiser/react-rpg.com/commits/refactor/code-cleanup

**Comment by ASteinheiser** [comment]
Closing this as the refactor will be merged soon.
