### ISSUE TITLE
Configure ESLint with additional rules

### ISSUE THREAD

**Issue by Alphanumber** [ASteinheiser/react-rpg.com#31]
Perhaps the project could use a linter? Might be good to investigate the various linters and decide if one would be useful to help with general code quality.

**Comment by ASteinheiser** [comment]
Currently we have es-lint installed by create-react-app. Is this sufficient or do you think we need something else?

**Comment by Alphanumber** [comment]
Sorry, I didn't realize the project was already using es-lint. I didn't see any .eslint configs so I wasn't sure any linting was being done currently.

**Comment by ASteinheiser** [comment]
I'm pretty sure the create-react-app enforces the same defaults for everyone depending on the react-scripts version? Could be wrong.
Either way, I agree. We will need an eslint config because I want to add some additional rules anyways.
Do you think we should have a .nvmrc as well?

**Comment by Alphanumber** [comment]
Ah, I see. I wasn't aware that create-react-app had its own default rules. Those rules seem rather permissive, though. Linting with popular style guides would normally paint my editor red.

Locking down node versions is probably a good idea, but also probably a good idea to upgrade node as necessary.

**Comment by ASteinheiser** [comment]
Yeah, definitely need to crank the settings up on the linter!

And sure, we will just have to make sure we update the .nvmrc when new versions come out.

**Comment by ASteinheiser** [comment]
@Alphanumber I have added an eslint config now, feel free to check it out on staging!
