### ISSUE TITLE
Possibly refactor the project structure?

### ISSUE THREAD

**Issue by ASteinheiser** [ASteinheiser/react-rpg.com#32]
I think, if this project is to scale, the structure will need to change. Whether that be a little or a lot, I'm not sure.
At a minimum I want to move some of the modules to a better location. Some of them belong co-located with the component that uses them.

**Comment by ASteinheiser** [comment]
Here's @JoniTech 's suggestion:
"When you plan to scale, divide by functionality instead, as in monsters / world / maps. Kind of how you structured your reduces(src/features) now."

**Comment by ASteinheiser** [comment]
@JoniTech So are you saying something like a `components / containers / redux` folder setup?

**Comment by JoniTech** [comment]
Yes, but do what works for you.

This is quite a self-contained app, so it's unlikely parts of it would get pulled out for any reason (like reuse). The divide by functionality might make it harder to find things.

The technical structure should make your life easier in maintaining and improving it.

**Comment by ASteinheiser** [comment]
I feel like I'm currently using a structure that is close to the normal technical structure, but I felt the need to call "containers" -> "features" since that is closer to what they are doing.

I'm not totally sold on doing the normal `components / containers / redux` setup, but I'm open to hearing justification for it or other suggestions for project structure.

**Comment by ASteinheiser** [comment]
After much refactoring on the `refactor/code-cleanup` branch, I think I found that I just needed to move all my loose action functions into an actions folder associated with each feature.
So we have:
`components`: re-usable UI elements
`config`: constants and redux store setup
`data`: json objects for items, monsters, and maps
`features`: essentially just `container`s with a `reducer` and `actions`
`modules`: helper functions shared across app

I feel like this is basically the same as the `components / containers / redux` setup, but just a little more tuned for this use case.

Do you have any additional thoughts @JoniTech

**Comment by JoniTech** [comment]
It's a small project. As long as you can easily find your way around the code-base this structure is fine.

I still think features and modules are a bit off. You might want to change modules to utils or helpers, depending on their function. Those are more common in React projects in my experience. 
And features maybe containers, if that's what they are.

**Comment by ASteinheiser** [comment]
Gotcha. I think utils instead of modules makes more sense.

The features are both a container and redux store though. I think I am pleased with the structure after changing modules -> utils and moving all the redux actions logic into their appropriate spot.

**Comment by ASteinheiser** [comment]
Going to close this general issue. I'll be merging in the refactor soon. If anyone has any specific things they want to refactor, create a new issue.
