### ISSUE TITLE
Fix removeEventListeners inside of useEffect

### ISSUE THREAD

**Issue by ASteinheiser** [ASteinheiser/react-rpg.com#39]
The functions being removed are anonymous functions declared inside the functional component, and therefore cannot be removed by reference. If anyone has a solution that includes keeping the useEffect, please share! Otherwise I think those components will have to be class components.

**Comment by Alaricus** [comment]
Which file is this in?

**Comment by ASteinheiser** [comment]
I believe this is happening in `src/features/player/controls`. I am not entirely sure that this is happening, but I was reading something on using `useEffect` with removeEventListener. How are you testing that the event listener is getting removed?

**Comment by Alaricus** [comment]
If you run `getEventListeners(window);` in the Chrome dev tools console, it'll return an object where each property is named for an event type and contains an array of listeners. Check it out.

**Comment by ASteinheiser** [comment]
@Alaricus That's awesome! Well, thank you for helping debug this "issue".

**Comment by ASteinheiser** [comment]
@allcontributors[bot] add @Alaricus for question and ideas
