### ISSUE TITLE
Opening a chest (or maybe leveling up?) turns game audio back on

### ISSUE THREAD

**Issue by adamhammes** [ASteinheiser/react-rpg.com#53]

**Comment by Alaricus** [comment]
Unable to recreate in the browser. Is this a mobile issue? If not what are the steps to recreate. Please provide more details.

**Comment by adamhammes** [comment]
Yeah,  I don't even know what I was thinking opening an issue without clearer reproduction instructions. Sorry if I bothered you!

**Comment by Alaricus** [comment]
Hey, you aren't bothering at all, I'm brand new here too and would love to help fix something. =) If you can figure out how to recreate it, please reopen this issue. I'm about to spend several hours in an airport and on a plane, so wouldn't mind digging in. Cheers!
