### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by markerikson** [ASteinheiser/react-rpg.com#6]
This is pretty neat!  Both in terms of the gameplay / visuals, and the actual implementation.

I skimmed through some parts of the code, and I do have some quick observations and suggestions:

- The pattern of creating a new potential state object before you've determined what the action type is is a bit unusual
- You're definitely mutating the existing state in a number of places, like this:  https://github.com/ASteinheiser/react-rpg.com/blob/407e65d78495af3a2f8c1c7583d10646f80dd3df/src/features/map/reducer.js#L26 .  That's because `Object.assign()` only does a shallow copy, and you're modifying the arrays and objects that were already inside it.
- Some parts of the reducer logic would benefit from use of the object spread operator, like here: https://github.com/ASteinheiser/react-rpg.com/blob/407e65d78495af3a2f8c1c7583d10646f80dd3df/src/features/player/reducer.js#L39-L51 .  That could become:

```js
return {
    ...state,
    playerMoved : !state.playerMoved,
    ...action.payload
}
```

- You definitely should _not_ directly import the store into your component files, like here: https://github.com/ASteinheiser/react-rpg.com/blob/407e65d78495af3a2f8c1c7583d10646f80dd3df/src/features/player/index.js#L47 .  Either pass those values to the component in your `mapState` function, or read them from the store using `getState()` in a thunk.  Ditto with other code that currently accesses the store, like [attack-monster.js](https://github.com/ASteinheiser/react-rpg.com/blob/407e65d78495af3a2f8c1c7583d10646f80dd3df/src/features/player/attack-monster.js) .See [the Redux FAQ entry on directly importing the store](https://redux.js.org/faq/store-setup#can-or-should-i-create-multiple-stores-can-i-import-my-store-directly-and-use-it-in-components-myself).  
- In general, I'd encourage you to take a look at our new [Redux Starter Kit package](https://redux-starter-kit.js.org).  I think it could help simplify a good chunk of your code, and it would also help detect (and help you prevent) those accidental state mutations.

All that said, congrats - you've clearly put a lot of time and effort into this, and it shows!  Hopefully these suggestions help you make the code a bit better.

**Comment by ASteinheiser** [comment]
@markerikson Thank you for your kind words!

I can definitely see what your saying with these suggestions and I appreciate you taking the time to review my code and point this out.

This definitely explains some the weird behavior I have been experiencing!

**Comment by ASteinheiser** [comment]
@markerikson Thanks again for the feedback. I have implemented your suggestions and it made a lot of code clear up. Please feel free to check it out on the staging branch at the moment, and let me know what you think!
