### ISSUE TITLE
Broken Tests - Surrounding Tiles

### ISSUE THREAD

**Issue by Saintroi** [ASteinheiser/react-rpg.com#67]
It seems like a lot of the tests in __tests__/utils/get-surrounding-tiles.js are broken based on some changes made to the get-surrounding-tiles util. 

The tests expect an array of surrounding tiles, but the util returns an object with "tiles" and "padding tiles." It seems like the majority of the tests are looking for the tiles component of that, so that's an easy fix, but the following tests are still broken with that change:

* "when startPos is out of bounds" expects **false** but the util returns:
```
{"paddingTiles": [[15, -3], [13, -2], [14, -2], [15, -2], [16, -2], [17, -2], [13, -1], [14, -1], [15, -1], [16, -1], [17, -1]], "tiles": [[12, 0], [13, 0], [14, 0], [15, 0], [16, 0], [17, 0], [18, 0], [13, 1], [14, 1], [15, 1], [16, 1], [17, 1], [13, 2], [14, 2], [15, 2], [16, 2], [17, 2], [15, 3]]}
```

* "startPos is top right corner: [0, 19]" expects an **array** but the util returns **false**

* "startPos is bottom right corner: [14, 19]" expects an **array** but the util returns **false**

* "startPos is bottom left corner: [14, 0]" expects this array:
```
[[11, 0], [12, 0], [13, 0], [14, 0], [12, 1], [13, 1], [14, 1], [12, 2], [13, 2], [14, 2], [14, 3]]
```
but the tiles array from the util is:
```
[[11, 0], [12, 0], [13, 0], [14, 0], [15, 0], [16, 0], [17, 0], [12, 1], [13, 1], [14, 1], [15, 1], [16, 1], [12, 2], [13, 2], [14, 2], [15, 2], [16, 2], [14, 3]]
```
which is close, but not correct.

I imagine something changed with how the util interprets the start positions and the tests weren't adjusted, willing to put in a fix if someone can explain to me what changed.

**Comment by ASteinheiser** [comment]
@Saintroi Hey, thanks for looking into this! I definitely messed up the tests during my big refactor, and one of the major things was changing this function. I really should have fixed it, but it slipped my mind.

I swapped the order (x, y) to (y, x) to conform with the rest of the code. This would explain those false values where there should be an array, and vice versa.

And you are correct that it no longer just returns an array of tiles. I needed to get both the tiles and padding tiles, so it now returns an object.

Please feel free to fix this. I believe the `surrounding-tiles.js` works perfectly, so you should be able to just make them all pass. You can add tests for padding tiles if you would like, but I'll accept a PR without it.

**Comment by Saintroi** [comment]
@ASteinheiser No problem! That makes sense, and changing that fixes some of these (some already seem corrected) but not all of them.

Does the map start in the top left corner? I see you're testing [0,0] as the top left, which means [0, 19] would be top right, [14, 0] would be bottom left, and [14, 19] would be bottom right, correct?

If I understand that correctly, then I also see that the map is limited by the numbers in the MAP_DIMENSIONS constant which are set at 15 and 20, which really are the out-of-bounds numbers as the map tiles start at 0. So there should be no tiles with a Y greater than 14 or an X greater than 19, correct?

In that instance, the startPos height > MAX_HEIGHT test case SHOULD be working, but it isn't. Here's the code:
```
test('startPos height > MAX_HEIGHT: [15, 0]', () => {
      const startPos = [MAP_DIMENSIONS[0], 0];

      expect(getSurroundingTiles(startPos)).toBeFalsy();
    });
```

And this expects false, but actually returns:
```
{"paddingTiles": [[15, -3], [13, -2], [14, -2], [15, -2], [16, -2], [17, -2], [13, -1], [14, -1], [15, -1], [16, -1], [17, -1]], "tiles": [[12, 0], [13, 0], [14, 0], [15, 0], [16, 0], [17, 0], [18, 0], [13, 1], [14, 1], [15, 1], [16, 1], [17, 1], [13, 2], [14, 2], [15, 2], [16, 2], [17, 2], [15, 3]]}
```

Which is weird, because the following test case checks the out of bounds on the X axis and does return false as expected:

```
test('startPos width > MAX_WIDTH: [0, 20]', () => {
      const startPos = [0, MAP_DIMENSIONS[1]];

      expect(getSurroundingTiles(startPos)).toBeFalsy();
    });
```

And ya know what, while writing this it just occurred to me to go look in get-surrounding-tiles.js myself and see if I can find the issue, and it's a pretty obvious one. Lines 26 and 27 are:
```
if(startPos[0] >= MAP_DIMENSIONS[1] || startPos[0] < 0
    || startPos[1] >= MAP_DIMENSIONS[0] || startPos[1] < 0) return false;
```

Which I'm sure you can see the error there in the MAP_DIMENSIONS indices which are backwards. Do you want me to make that change and push it up in a PR along with the changes I've made to the tests? Or would you rather have that fix separate from the tests?

**Comment by ASteinheiser** [comment]
Okay, so the code is actually correct. In my initial response, I said that I had switched the order (x, y) to (y, x), which should explain the falsy values being objects. Swap those values in the test, and it should work.

If you open the redux store, you can see the player moving width-wise will make position 0 in the player's position array increment. MAP_DIMENSIONS[1] has the width, so that check should be correct on lines 26/27.

I think in the future, something we could do to solve all this confusion would be to just pass around object with x and y keys for position.

**Comment by Saintroi** [comment]
I think we need to clarify where the (x, y) standard was swapped to (y, x) and where it wasn't, because if it's supposed to be everywhere then the only thing that should need changing is the tests, like you said. 

If you read through my message above you'll see that I already have changed the tests to follow the 
(y, x) format and they didn't all work based on that change alone.

Based on that conditional in get-surrounding-tiles.js, startPos is (x, y) and MAP_DIMENSIONS is (y, x), if this is correct then I suggest we swap one format to the other or do as you said and convert to an object with x and y keys.

**To try and be super clear here:**
 The reason we get an object instead of false when the startPos value [15, 0] is sent is because that conditional is comparing that 15 with the 20 from the MAP_DIMENSIONS[1] rather than MAP_DIMENSIONS[0] which is 15

The reason false on [0, 20] occurs is because that conditional is comparing 20 to the 15 from MAP_DIMENSIONS[0] which is the incorrect value but 20>=15 is true so it returns false.

I will submit a PR with what I believe is a fix and we can go from there!

**Comment by Saintroi** [comment]
The more I look at the code the more confused I get lmao

The main section of the get-surrounding-tiles.js file is pretty small so I'll paste it here, I think I understand what you're saying in that the code is correct, but with that all of the variable names are now incorrect which makes it pretty confusing to read lol. 

```
/ takes an array of relative coordinates to the map size (20 x 15) i.e. [1, 1]
export default function getSurroundingTiles(newPos) {
  // make sure the new position is in relative map tile size
  const x = newPos[0] % SPRITE_SIZE === 0 ? newPos[0] / SPRITE_SIZE : newPos[0];
  const y = newPos[1] % SPRITE_SIZE === 0 ? newPos[1] / SPRITE_SIZE : newPos[1];
  // set tile to relative tile position
  const startPos = [x, y];
  // make sure the start position is within the bounds
  if(startPos[0] >= MAP_DIMENSIONS[1] || startPos[0] < 0
    || startPos[1] >= MAP_DIMENSIONS[0] || startPos[1] < 0) return false;
  // then calculate the surrounding tiles according to the bounds
  const surroundingTiles = [];
  const paddingTiles = [];
  // add position as offset to each radius tile
  radiusTiles().forEach(({x, y}) => {
    // get radius with location as offset
    const offsetX = x + startPos[0];
    const offsetY = y + startPos[1];
    // if it is inside the bounds
    if(offsetX >= 0 && offsetX < MAP_DIMENSIONS[1]
      && offsetY >= 0 && offsetY < MAP_DIMENSIONS[0]) {
      // add to surrounding tile...
      surroundingTiles.push([offsetX, offsetY]);
    } // otherwise add the tile to padding tiles array
    else {
      paddingTiles.push([offsetX, offsetY]);
    }
  });
```

I'm going to go through and swap x and y in this code, just changing the variable names so everything matches up with (y, x), and then try to understand where the problem is.

**Comment by Saintroi** [comment]
As you can see above I have created PR #68 and provided comments. This is not a fix as there are either issues in the code or there is something I'm not understanding / we aren't really using (y, x) everywhere.

**Comment by ASteinheiser** [comment]
@Saintroi Thanks for the observations. I will look into your changes ASAP, as well as making it more concise on where it's (x, y) and (y, x). To start, I think I might just change the MAP_DIMENSIONS Array to be an Object. I'll try to figure out why those other tests are failing too.
